### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by MrMeison**
Add typescript definitions for project, fix jshint issues

### CODE REVIEW

**Comment by tgabi333** [comment]
@MrMeison, could you please remove the `@types/webrtc` dependencies here also as in SimpleWebRTC?

@fippo or @HenrikJoreteg could you please authorize me to handle this package? (npm too)

**Comment by MrMeison** [comment]
@tgabi333 , yes, I can. Check PR again, please

**Comment by MrMeison** [comment]
Could you please update status for this PR?

**Comment by adelgado** [comment]
Is there anything missing for this PR to be merged?

**Comment by adelgado** [comment]
:-(

**Pull request closed without merging**
