### PR TITLE
Add unprefixed RTCPeerConnection

### LINKED ISSUE #18: support unprefixed vendors
there are plenty of vendors in the wild without prefixes (iosrtc) so why does this not work with those?

### PR DESCRIPTION
**Pull request by RangerMauve**
Fixes #18

### CODE REVIEW

**Comment by fippo** [comment]
hah, saw this just now. Thanks!

**Comment by RangerMauve** [comment]
I made it just now, too. :D

**Comment by fippo** [comment]
published as 2.1.3 -- no changes in documented behaviour.

**Comment by RangerMauve** [comment]
Awesome!

**Pull request merged**
