### PR TITLE
removes the assumption that navigator.userAgent matches Chrom(e|ium)

### PR DESCRIPTION
**Pull request by fippo**
@legastero @tommoor

### CODE REVIEW

**Comment by tommoor** [comment]
Heh, was going to do it like this which would leave version undefined rather than false... but honestly, as long as it works :smile: 

https://github.com/HenrikJoreteg/webrtcsupport/compare/master...tommoor:master

**Comment by fippo** [comment]
btw, @xdumaine -- you might hit that too.

Fixed in 2.1.1 and 1.3.1 respectively. Thanks!

**Comment by tommoor** [comment]
@fippo bad news. ```"Uncaught ReferenceError: navіgator is not defined"```

**Comment by fippo** [comment]
grmbl... 2.1.2 and 1.3.2 will be up soon...

**Comment by fippo** [comment]
so... how did 
```
var getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.msGetUserMedia || navigator.mozGetUserMedia;
```
work?

**Comment by tommoor** [comment]
Have a look at the highlighting of navigator here:

https://github.com/HenrikJoreteg/webrtcsupport/blob/master/index-browser.js

the new 'navigator' isn't highlighted - something up with it?

**Comment by fippo** [comment]
UTF8-madness...

**Comment by fippo** [comment]
ok, updated versions are out

**Pull request merged**
