### PR TITLE
better checking for support of data channel

### LINKED ISSUE #21: supportDataChannel no longer works
https://github.com/HenrikJoreteg/webrtcsupport/blob/master/index-browser.js#L34

`window.RTCPeerConnection.prototype.createDataChannel` no longer exists. :confused:

### PR DESCRIPTION
**Pull request by xdumaine**
Resolves #21 @fippo

### CODE REVIEW

**Comment by fippo** [comment]
i still don't understand where you are not seeing createDataChannel on the prototype. Instantiating a peerconnection is something i'd prefer to avoid

**Comment by xdumaine** [comment]
Looks like it's because of adapter.js the `RTCPeerConnection` added to `window` does not have `createDataChannel` on the prototype. Someone mentioned it was deprecated, is that accurate? @fippo Open https://webrtc.github.io/samples/src/content/peerconnection/pc1/ and run `window.RTCPeerConnection.prototype.createDataChannel` in the console - undefined.

**Comment by fippo** [comment]
ah... adapter wraps RTCPeerConnection in a way which breaks this. Might be quite some effort to fix that... hm.

But 2/3 browsers support the datachannel, this module is a thing of the past.

createDataChannel is still a thing AFAIK

**Comment by xdumaine** [comment]
I'm fine with closing these then. It's an issue with adapter, if at all.

**Pull request closed without merging**
